# -*- coding: utf-8 -*-
"""rtl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vq7yX7I1avGXbEFgJ40z6Us6YNFFRiSt
"""

import pandas as pd
import numpy as np
import random
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
import joblib

# Load dataset
df = pd.read_csv("engineered_rtl_dataset.csv")

# Define features and target
X = df.drop(columns=["logic_depth"])
y = df["logic_depth"]

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train the Random Forest model
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate performance
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f"Model Performance:\nMSE: {mse}\nR² Score: {r2}")

# Save model
joblib.dump(model, "final_random_forest_model.pkl")

# Example prediction on new data
loaded_model = joblib.load("final_random_forest_model.pkl")
new_data = np.array(X_test.iloc[0]).reshape(1, -1)
prediction = loaded_model.predict(new_data)
print(f"Predicted Combinational Depth: {prediction[0]}")

print(f"Predicted Combinational Depth: {prediction[0]}")
print(f"Actual Combinational Depth: {y_test.iloc[0]}")